version: "3.8"
services:
  pickgether-redis:
    container_name: pickgether-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: moonsungkim/pickgether-redis
    ports:
      - "6379:6379"
  pickgether-database:
    container_name: pickgether-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: moonsungkim/pickgether-database
    environment:
      - MYSQL_DATABASE=pickgether
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/my.conf
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
networks:
  springboot-mysql-net:
    driver: bridge