spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common

#...

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pickgether
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pickgether-db.c7mckvmhchzp.ap-northeast-2.rds.amazonaws.com:3306/pickgether_db
    username: moon
    password: 12345678
  redis:
    host: redis-14928.c90.us-east-1-3.ec2.cloud.redislabs.com
    port: 14928
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
